stages:
  complete-speed_based_filter:
    cmd: dz run-step speed_based_filter complete
    deps:
    - data/gpsping/ubermedia/complete/extended_ping
    - src/speed_based_filter.py
    params:
    - zimmer.yaml:
      - envs.complete.params.speed_based_filter.max_speed
      - envs.complete.params.speed_based_filter.min_pings_by_device
    outs:
    - data/mobility/speed_based_filter/complete/drop_stat.parquet
    - data/mobility/speed_based_filter/complete/ping_with_arrival
  small-speed_based_filter:
    cmd: dz run-step speed_based_filter small
    deps:
    - data/gpsping/ubermedia/non_covid_tuesday/extended_ping
    - src/speed_based_filter.py
    params:
    - zimmer.yaml:
      - envs.complete.params.speed_based_filter.max_speed
      - envs.complete.params.speed_based_filter.min_pings_by_device
    outs:
    - data/mobility/speed_based_filter/small/drop_stat.parquet
    - data/mobility/speed_based_filter/small/ping_with_arrival
  complete-initial_stops:
    cmd: dz run-step initial_stops complete
    deps:
    - data/mobility/speed_based_filter/complete/ping_with_arrival
    - src/initial_stops.py
    params:
    - zimmer.yaml:
      - envs.complete.params.initial_stops.distance_metric
      - envs.complete.params.initial_stops.max_time_between
      - envs.complete.params.initial_stops.min_size
      - envs.complete.params.initial_stops.min_staying_time
      - envs.complete.params.initial_stops.r1
      - envs.complete.params.initial_stops.r2
    outs:
    - data/mobility/initial_stops/complete/stop
  small-initial_stops:
    cmd: dz run-step initial_stops small
    deps:
    - data/mobility/speed_based_filter/small/ping_with_arrival
    - src/initial_stops.py
    params:
    - zimmer.yaml:
      - envs.complete.params.initial_stops.distance_metric
      - envs.complete.params.initial_stops.max_time_between
      - envs.complete.params.initial_stops.min_size
      - envs.complete.params.initial_stops.min_staying_time
      - envs.complete.params.initial_stops.r1
      - envs.complete.params.initial_stops.r2
    outs:
    - data/mobility/initial_stops/small/stop
  complete-filtered_stops:
    cmd: dz run-step filtered_stops complete
    deps:
    - data/mobility/initial_stops/complete/stop
    - src/filtered_stops.py
    params:
    - zimmer.yaml:
      - envs.complete.params.filtered_stops.min_destinations
      - envs.complete.params.filtered_stops.min_stops_to_count
    outs:
    - data/mobility/filtered_stops/complete/stop
  small-filtered_stops:
    cmd: dz run-step filtered_stops small
    deps:
    - data/mobility/initial_stops/small/stop
    - src/filtered_stops.py
    params:
    - zimmer.yaml:
      - envs.complete.params.filtered_stops.min_destinations
      - envs.complete.params.filtered_stops.min_stops_to_count
    outs:
    - data/mobility/filtered_stops/small/stop
  complete-device_counties:
    cmd: dz run-step device_counties complete
    deps:
    - data/mobility/filtered_stops/complete/stop
    - src/device_counties.py
    params:
    - zimmer.yaml:
      - envs.complete.params.device_counties.min_locale_rate
    outs:
    - data/mobility/device_counties/complete/device_county.parquet
  small-device_counties:
    cmd: dz run-step device_counties small
    deps:
    - data/mobility/filtered_stops/small/stop
    - src/device_counties.py
    params:
    - zimmer.yaml:
      - envs.complete.params.device_counties.min_locale_rate
    outs:
    - data/mobility/device_counties/small/device_county.parquet
  complete-h3_hour_aggregate:
    cmd: dz run-step h3_hour_aggregate complete
    deps:
    - data/gpsping/ubermedia/complete/extended_ping
    - src/h3_hour_aggregate.py
    params:
    - zimmer.yaml:
      - envs.complete.params.h3_hour_aggregate.min_count
      - envs.complete.params.h3_hour_aggregate.min_duration
    outs:
    - data/mobility/h3_hour_aggregate/complete/hash_hour
  small-h3_hour_aggregate:
    cmd: dz run-step h3_hour_aggregate small
    deps:
    - data/gpsping/ubermedia/non_covid_tuesday/extended_ping
    - src/h3_hour_aggregate.py
    params:
    - zimmer.yaml:
      - envs.complete.params.h3_hour_aggregate.min_count
      - envs.complete.params.h3_hour_aggregate.min_duration
    outs:
    - data/mobility/h3_hour_aggregate/small/hash_hour
  complete-semantic_stops:
    cmd: dz run-step semantic_stops complete
    deps:
    - data/mobility/filtered_stops/complete/stop
    - src/semantic_stops.py
    params:
    - zimmer.yaml:
      - envs.complete.params.home_arrive
      - envs.complete.params.morning_end
      - envs.complete.params.semantic_stops.min_home_hours
      - envs.complete.params.semantic_stops.min_work_hours
      - envs.complete.params.semantic_stops.time_unit
      - envs.complete.params.work_end
    outs:
    - data/mobility/semantic_stops/complete/semantic_stop
  small-semantic_stops:
    cmd: dz run-step semantic_stops small
    deps:
    - data/mobility/filtered_stops/small/stop
    - src/semantic_stops.py
    params:
    - zimmer.yaml:
      - envs.complete.params.home_arrive
      - envs.complete.params.morning_end
      - envs.complete.params.semantic_stops.time_unit
      - envs.complete.params.work_end
      - envs.small.params.semantic_stops.min_home_hours
      - envs.small.params.semantic_stops.min_work_hours
    outs:
    - data/mobility/semantic_stops/small/semantic_stop
  complete-stop_reporting:
    cmd: dz run-step stop_reporting complete
    deps:
    - data/gpsping/ubermedia/complete/extended_ping
    - data/mobility/filtered_stops/complete/stop
    - data/mobility/initial_stops/complete/stop
    - src/stop_reporting.py
    outs:
    - reports/complete/stop_look.md:
        cache: false
  small-stop_reporting:
    cmd: dz run-step stop_reporting small
    deps:
    - data/gpsping/ubermedia/non_covid_tuesday/extended_ping
    - data/mobility/filtered_stops/small/stop
    - data/mobility/initial_stops/small/stop
    - src/stop_reporting.py
    outs:
    - reports/small/stop_look.md:
        cache: false
