stages:
  get_device_counties:
    cmd: python -m src get_device_counties
    deps:
    - data/um/ping
    - src/get_device_counties.py
    params:
    - min_locale_rate
    outs:
    - data/get_device_counties/device_county.parquet
  get_device_days:
    cmd: python -m src get_device_days
    deps:
    - data/um/ping
    - src/get_device_days.py
    params:
    - get_device_days.am_end
    - get_device_days.am_start
    - get_device_days.pm_end
    - get_device_days.pm_start
    outs:
    - data/get_device_days/device_day
  create_filtered_dataset:
    cmd: python -m src create_filtered_dataset
    deps:
    - data/get_device_counties/device_county.parquet
    - data/get_device_days/device_day
    - data/um/ping
    - src/create_filtered_dataset.py
    params:
    - create_filtered_dataset.min_am
    - create_filtered_dataset.min_pm
    - create_filtered_dataset.min_reliable_days
    - create_filtered_dataset.min_sum
    - create_filtered_dataset.specific_to_locale
    - min_locale_rate
    outs:
    - data/create_filtered_dataset/filtered_ping
  stop_detection:
    cmd: python -m src stop_detection
    deps:
    - data/create_filtered_dataset/filtered_ping
    - src/stop_detection.py
    params:
    - stop_detection.distance_metric
    - stop_detection.home_arrive
    - stop_detection.home_depart
    - stop_detection.max_time_between
    - stop_detection.min_size
    - stop_detection.min_staying_time
    - stop_detection.min_work_hours
    - stop_detection.r1
    - stop_detection.r2
    - stop_detection.work_end
    - stop_detection.work_start
    outs:
    - data/stop_detection/stop
