get_device_days:
  am_start: 5
  am_end: 10
  pm_start: 16
  pm_end: 20
create_filtered_dataset:
  min_am: 5
  min_pm: 5
  min_sum: 50
  min_reliable_days: 1
  specific_to_locale: 
    - "Budapest"
    - "Pest"
min_locale_rate: 0.8
